// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GentlemenChoice.Data.Models;

public partial class ProductVoucher
{
    public int ProductVoucherId { get; set; }

    public int? ProductId { get; set; }

    public int? VoucherId { get; set; }

    public virtual Product Product { get; set; }

    public virtual Voucher Voucher { get; set; }
}