// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GentlemenChoice.Data.Models;

public partial class Shipment
{
    public int ShipmentId { get; set; }

    public int? OrderId { get; set; }

    public string ShippingAddress { get; set; }

    public decimal ShippingCost { get; set; }

    public DateTime? ShippingDate { get; set; }

    public DateTime? EstimatedDeliveryDate { get; set; }

    public string DeliveryStatus { get; set; }

    public virtual Order Order { get; set; }
}