// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GentlemenChoice.Data.Models;

public partial class Voucher
{
    public int VoucherId { get; set; }

    public string Code { get; set; }

    public decimal DiscountAmount { get; set; }

    public string DiscountType { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int UsageLimit { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<ProductVoucher> ProductVouchers { get; set; } = new List<ProductVoucher>();
}